apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether.fullname" . }}-api
  labels:
    {{- include "aether.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "aether.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
