apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether.fullname" . }}-web
  labels:
    {{- include "aether.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.web.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "aether.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
